spring:
  profiles:
    # 默认激活 dev 环境
    active: dev
jwt:
  # 签发人
  issuer: yulu
  # 秘钥
  secret: GWq2ICzFQ+vNctDi1PWjT3qLxC9Us4fGr7Iyq3i/yVSp3Z2ciU+quM6Bu8NCy7uSa03Bblkdra3qwnZxpMOGFA==
  # token 过期时间（单位：分钟） 24*60
  tokenExpireTime: 1440
  # token 请求头中的 key 值
  tokenHeaderKey: Authorization
  # token 请求头中的 value 值前缀
  tokenPrefix: Bearer

